---
title: "shiny_logs"
author: "Jake Eisaguirre"
date: "2023-01-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages

librarian::shelf(tidyverse, here, janitor, purrr, learnitdown, tidyr, stringr)

```


# In the terminal or code chunk run bash function `load_logs` to pull logs folder from EC2 server to local machine
```{bash, engine.opts='-l'}

load_logs

```


# load logs of interest
```{r}

files <- list.files(here("logs"))

data <- data.frame()

for (i in seq_along(files)){

  temp <- read_shinylogs(here("logs", files[i]))
    
  data <- rbind(data, temp)

}
```


# search log for `download_btn` and inspect logs for `user` and `session`
```{r}

dwnld <- data %>% 
  select(session, date, user, label, value) %>% 
  separate_longer_delim(value, ',') %>% 
  filter(str_detect(label,"download_btn") | 
         str_detect(label, "auth-user")) %>% 
  mutate(value = str_remove_all(value, "list"),
         value = str_remove_all(value, ","),
         value = str_remove_all(value, "\\("),
         value = str_remove_all(value, "\\)")) %>% 
  filter(duplicated(session))
```


# inspect `location` and `region` values by `session` of interest
```{r}
log <- data %>% 
  select(session, date, user, label, value) %>% 
  separate_longer_delim(value, ',') %>%
  filter(session == "9804bebf52e270ba6fb8c406cbbe8c54", #insert session id of interest
         label %in% c("location", "region", "region_hobo", "location_hobo")) %>% 
  mutate(value = str_remove_all(value, "list"),
         value = str_remove_all(value, ","),
         value = str_remove_all(value, "\\("),
         value = str_remove_all(value, "\\)")) 
```

# visualize data
```{r}



```

